sudo: false
language: node_js
node_js:
  - "node"

branches:
  only:
    - develop

services:
  - docker

before_script:
  - npm run-script lint

script:
  - docker build -t apinf/platform:$DOCKER_TAG .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push apinf/platform:$DOCKER_TAG
